import { PrismaClient, FoodCategory, GoalCategory, MovementPattern, ExerciseDifficulty } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const equipmentData = ["Barbell", "Dumbbells", "Bench", "Cable Machine", "Smith Machine", "Squat Rack", "Leg Press", "Pull-up Bar", "Resistance Bands", "Cardio Machines", "Weight Machines", "Bodyweight Only"];
  const equipment = Object.fromEntries(await Promise.all(equipmentData.map(async (name) => [name, await prisma.equipment.upsert({ where: { slug: slug(name) }, update: {}, create: { name, slug: slug(name) } })] as const)));

  const foodData = [
    { name: "Greek yogurt", slug: "greek-yogurt", category: FoodCategory.DAIRY, servingSize: 200, servingUnit: "g", calories: 130, protein: 20, carbohydrates: 8, fat: 2, fiber: 0, estimatedCost: 1.25, currency: "USD", isVegetarian: true, isVegan: false, containsEgg: false, allergens: ["milk"] },
    { name: "Firm tofu", slug: "firm-tofu", category: FoodCategory.LEGUME, servingSize: 150, servingUnit: "g", calories: 216, protein: 23, carbohydrates: 5, fat: 13, fiber: 3, estimatedCost: 1.1, currency: "USD", isVegetarian: true, isVegan: true, containsEgg: false, allergens: ["soy"] },
    { name: "Cottage cheese", slug: "cottage-cheese", category: FoodCategory.DAIRY, servingSize: 150, servingUnit: "g", calories: 147, protein: 18, carbohydrates: 6, fat: 5, fiber: 0, estimatedCost: 1.4, currency: "USD", isVegetarian: true, isVegan: false, containsEgg: false, allergens: ["milk"] },
    { name: "Chicken breast", slug: "chicken-breast", category: FoodCategory.PROTEIN, servingSize: 150, servingUnit: "g", calories: 248, protein: 46, carbohydrates: 0, fat: 5, fiber: 0, estimatedCost: 2.35, currency: "USD", isVegetarian: false, isVegan: false, containsEgg: false, allergens: [] },
    { name: "Quinoa, cooked", slug: "quinoa-cooked", category: FoodCategory.GRAIN, servingSize: 150, servingUnit: "g", calories: 180, protein: 6.6, carbohydrates: 32, fat: 2.9, fiber: 4.2, estimatedCost: 0.7, currency: "USD", isVegetarian: true, isVegan: true, containsEgg: false, allergens: [] },
    { name: "Salmon", slug: "salmon", category: FoodCategory.PROTEIN, servingSize: 140, servingUnit: "g", calories: 288, protein: 31, carbohydrates: 0, fat: 17, fiber: 0, estimatedCost: 3.5, currency: "USD", isVegetarian: false, isVegan: false, containsEgg: false, allergens: ["fish"] },
    { name: "Rolled oats", slug: "rolled-oats", category: FoodCategory.GRAIN, servingSize: 40, servingUnit: "g", calories: 152, protein: 5.1, carbohydrates: 27, fat: 3, fiber: 4, estimatedCost: 0.18, currency: "USD", isVegetarian: true, isVegan: true, containsEgg: false, allergens: [] },
    { name: "Blueberries", slug: "blueberries", category: FoodCategory.FRUIT, servingSize: 80, servingUnit: "g", calories: 46, protein: 0.6, carbohydrates: 11.6, fat: 0.3, fiber: 1.9, estimatedCost: 0.65, currency: "USD", isVegetarian: true, isVegan: true, containsEgg: false, allergens: [] },
    { name: "Banana", slug: "banana", category: FoodCategory.FRUIT, servingSize: 118, servingUnit: "g", calories: 105, protein: 1.3, carbohydrates: 27, fat: 0.4, fiber: 3.1, estimatedCost: 0.25, currency: "USD", isVegetarian: true, isVegan: true, containsEgg: false, allergens: [] },
    { name: "Brown rice, cooked", slug: "brown-rice-cooked", category: FoodCategory.GRAIN, servingSize: 150, servingUnit: "g", calories: 185, protein: 4.1, carbohydrates: 38, fat: 1.5, fiber: 2.7, estimatedCost: 0.32, currency: "USD", isVegetarian: true, isVegan: true, containsEgg: false, allergens: [] },
    { name: "Lentils, cooked", slug: "lentils-cooked", category: FoodCategory.LEGUME, servingSize: 150, servingUnit: "g", calories: 174, protein: 13.5, carbohydrates: 30, fat: 0.6, fiber: 11.9, estimatedCost: 0.38, currency: "USD", isVegetarian: true, isVegan: true, containsEgg: false, allergens: [] },
    { name: "Eggs", slug: "eggs", category: FoodCategory.PROTEIN, servingSize: 100, servingUnit: "g", calories: 143, protein: 13, carbohydrates: 0.7, fat: 9.5, fiber: 0, estimatedCost: 0.65, currency: "USD", isVegetarian: true, isVegan: false, containsEgg: true, allergens: ["egg"] },
    { name: "Spinach", slug: "spinach", category: FoodCategory.VEGETABLE, servingSize: 100, servingUnit: "g", calories: 23, protein: 2.9, carbohydrates: 3.6, fat: 0.4, fiber: 2.2, estimatedCost: 0.45, currency: "USD", isVegetarian: true, isVegan: true, containsEgg: false, allergens: [] },
    { name: "Broccoli", slug: "broccoli", category: FoodCategory.VEGETABLE, servingSize: 100, servingUnit: "g", calories: 34, protein: 2.8, carbohydrates: 6.6, fat: 0.4, fiber: 2.6, estimatedCost: 0.4, currency: "USD", isVegetarian: true, isVegan: true, containsEgg: false, allergens: [] },
    { name: "Sweet potato", slug: "sweet-potato", category: FoodCategory.VEGETABLE, servingSize: 150, servingUnit: "g", calories: 135, protein: 2.4, carbohydrates: 31, fat: 0.2, fiber: 5, estimatedCost: 0.45, currency: "USD", isVegetarian: true, isVegan: true, containsEgg: false, allergens: [] },
    { name: "Almonds", slug: "almonds", category: FoodCategory.NUT_SEED, servingSize: 28, servingUnit: "g", calories: 164, protein: 6, carbohydrates: 6.1, fat: 14.2, fiber: 3.5, estimatedCost: 0.58, currency: "USD", isVegetarian: true, isVegan: true, containsEgg: false, allergens: ["tree nut", "almond"] },
    { name: "Almond butter", slug: "almond-butter", category: FoodCategory.NUT_SEED, servingSize: 16, servingUnit: "g", calories: 98, protein: 3.4, carbohydrates: 3, fat: 8.9, fiber: 1.6, estimatedCost: 0.36, currency: "USD", isVegetarian: true, isVegan: true, containsEgg: false, allergens: ["tree nut", "almond"] },
    { name: "Olive oil", slug: "olive-oil", category: FoodCategory.OIL_CONDIMENT, servingSize: 5, servingUnit: "g", calories: 44, protein: 0, carbohydrates: 0, fat: 5, fiber: 0, estimatedCost: 0.08, currency: "USD", isVegetarian: true, isVegan: true, containsEgg: false, allergens: [] },
    { name: "Whole wheat bread", slug: "whole-wheat-bread", category: FoodCategory.GRAIN, servingSize: 40, servingUnit: "g", calories: 101, protein: 4, carbohydrates: 17, fat: 1.5, fiber: 2.7, estimatedCost: 0.28, currency: "USD", isVegetarian: true, isVegan: true, containsEgg: false, allergens: ["wheat", "gluten"] },
    { name: "Paneer", slug: "paneer", category: FoodCategory.DAIRY, servingSize: 100, servingUnit: "g", calories: 265, protein: 18.3, carbohydrates: 1.2, fat: 20.8, fiber: 0, estimatedCost: 1.1, currency: "USD", isVegetarian: true, isVegan: false, containsEgg: false, allergens: ["milk"] },
    { name: "Chickpeas, cooked", slug: "chickpeas-cooked", category: FoodCategory.LEGUME, servingSize: 150, servingUnit: "g", calories: 246, protein: 13.3, carbohydrates: 41, fat: 3.9, fiber: 11.3, estimatedCost: 0.42, currency: "USD", isVegetarian: true, isVegan: true, containsEgg: false, allergens: [] },
  ];
  const foods = Object.fromEntries(await Promise.all(foodData.map(async (data) => [data.slug, await prisma.food.upsert({ where: { slug: data.slug }, update: data, create: data })] as const)));

  const goalLabels: [GoalCategory, string][] = [[GoalCategory.MUSCLE_GAIN,"Muscle Gain"],[GoalCategory.FAT_LOSS,"Fat Loss"],[GoalCategory.WEIGHT_LOSS,"Weight Loss"],[GoalCategory.WEIGHT_GAIN,"Weight Gain"],[GoalCategory.RECOMPOSITION,"Body Recomposition"],[GoalCategory.STRENGTH,"Strength"],[GoalCategory.ENDURANCE,"Endurance"],[GoalCategory.GENERAL_FITNESS,"General Fitness"]];
  for (const [category,label] of goalLabels) await prisma.fitnessGoalOption.upsert({ where: { category }, update: { label }, create: { category, label } });
  for (const [slugValue,name,description] of [["no-restriction","No Restriction","No specific dietary pattern"],["vegetarian","Vegetarian","Plant-forward, including dairy and eggs"],["vegan","Vegan","Excludes animal-derived foods"],["eggetarian","Eggetarian","Vegetarian with eggs"],["custom","Custom","A personal dietary preference"]]) await prisma.dietPreference.upsert({ where: { slug: slugValue }, update: { name, description }, create: { slug: slugValue, name, description } });
  const physiqueData = [["lean-body","Lean Body","Light, defined lines"],["muscular-body","Muscular Body","Strong, built frame"],["athletic-body","Athletic Body","Balanced and active"],["bulky-body","Bulky Body","Powerful, solid build"],["weight-loss-body","Weight-Loss Body","A lighter, leaner shape"],["bodybuilder-physique","Bodybuilder Physique","Highly developed muscle"]];
  for (const [slugValue,name,description] of physiqueData) await prisma.physiqueGoalOption.upsert({ where: { slug: slugValue }, update: { name, description }, create: { slug: slugValue, name, description } });

  const exerciseData = [
    { name: "Barbell bench press", slug: "barbell-bench-press", primaryMuscle: "Chest", secondaryMuscles: ["Triceps","Front deltoids"], movementPattern: MovementPattern.HORIZONTAL_PUSH, difficulty: ExerciseDifficulty.INTERMEDIATE, instructions: ["Set shoulder blades against the bench.","Lower the bar with control to mid-chest.","Press smoothly while keeping feet planted."], safetyNotes: ["Use a spotter for challenging loads."], equipment: ["Barbell","Bench"] },
    { name: "Dumbbell floor press", slug: "dumbbell-floor-press", primaryMuscle: "Chest", secondaryMuscles: ["Triceps"], movementPattern: MovementPattern.HORIZONTAL_PUSH, difficulty: ExerciseDifficulty.BEGINNER, instructions: ["Lie on the floor with knees bent.","Lower elbows gently to the floor.","Press dumbbells overhead with control."], safetyNotes: ["Choose a load you can safely bring to the floor."], equipment: ["Dumbbells"] },
    { name: "Push-up", slug: "push-up", primaryMuscle: "Chest", secondaryMuscles: ["Triceps","Core"], movementPattern: MovementPattern.HORIZONTAL_PUSH, difficulty: ExerciseDifficulty.BEGINNER, instructions: ["Place hands just wider than shoulders.","Keep a straight line from head to heels.","Lower with control and press away."], safetyNotes: ["Modify at an incline if needed."], equipment: ["Bodyweight Only"] },
    { name: "Dumbbell goblet squat", slug: "dumbbell-goblet-squat", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes","Core"], movementPattern: MovementPattern.SQUAT, difficulty: ExerciseDifficulty.BEGINNER, instructions: ["Hold one dumbbell close to your chest.","Sit hips down between knees.","Stand tall through the whole foot."], safetyNotes: ["Use a comfortable range of motion."], equipment: ["Dumbbells"] },
    { name: "Lat pulldown", slug: "lat-pulldown", primaryMuscle: "Back", secondaryMuscles: ["Biceps"], movementPattern: MovementPattern.VERTICAL_PULL, difficulty: ExerciseDifficulty.BEGINNER, instructions: ["Take a comfortable overhand grip.","Pull the bar toward upper chest.","Return slowly to the start."], safetyNotes: ["Avoid pulling behind the neck."], equipment: ["Cable Machine"] },
    { name: "Dumbbell row", slug: "dumbbell-row", primaryMuscle: "Back", secondaryMuscles: ["Biceps"], movementPattern: MovementPattern.HORIZONTAL_PULL, difficulty: ExerciseDifficulty.BEGINNER, instructions: ["Brace one hand on a bench.","Pull the dumbbell toward your hip.","Lower slowly without twisting."], safetyNotes: ["Keep your back comfortably neutral."], equipment: ["Dumbbells","Bench"] },
    { name: "Dumbbell shoulder press", slug: "dumbbell-shoulder-press", primaryMuscle: "Shoulders", secondaryMuscles: ["Triceps"], movementPattern: MovementPattern.VERTICAL_PUSH, difficulty: ExerciseDifficulty.INTERMEDIATE, instructions: ["Start with dumbbells at shoulder height.","Press overhead without arching your back.","Lower with control."], safetyNotes: ["Use a comfortable range of motion."], equipment: ["Dumbbells"] },
    { name: "Dumbbell lateral raise", slug: "dumbbell-lateral-raise", primaryMuscle: "Shoulders", secondaryMuscles: [], movementPattern: MovementPattern.OTHER, difficulty: ExerciseDifficulty.BEGINNER, instructions: ["Stand tall with light dumbbells at your sides.","Raise arms to a comfortable height.","Lower slowly."], safetyNotes: ["Avoid swinging the weights."], equipment: ["Dumbbells"] },
    { name: "Dumbbell biceps curl", slug: "dumbbell-biceps-curl", primaryMuscle: "Biceps", secondaryMuscles: ["Forearms"], movementPattern: MovementPattern.OTHER, difficulty: ExerciseDifficulty.BEGINNER, instructions: ["Keep elbows near your sides.","Curl the dumbbells without swinging.","Lower through a controlled range."], safetyNotes: ["Choose a load that keeps the movement controlled."], equipment: ["Dumbbells"] },
    { name: "Overhead triceps extension", slug: "overhead-triceps-extension", primaryMuscle: "Triceps", secondaryMuscles: ["Shoulders"], movementPattern: MovementPattern.VERTICAL_PUSH, difficulty: ExerciseDifficulty.BEGINNER, instructions: ["Hold one dumbbell securely overhead.","Bend elbows to lower behind your head.","Extend smoothly back up."], safetyNotes: ["Keep elbows in a comfortable position."], equipment: ["Dumbbells"] },
    { name: "Romanian deadlift", slug: "romanian-deadlift", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes","Back"], movementPattern: MovementPattern.HINGE, difficulty: ExerciseDifficulty.INTERMEDIATE, instructions: ["Stand with the bar close to your legs.","Hinge hips back with a soft knee bend.","Stand tall by driving hips forward."], safetyNotes: ["Keep the load close and spine neutral."], equipment: ["Barbell"] },
    { name: "Dumbbell Romanian deadlift", slug: "dumbbell-romanian-deadlift", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes"], movementPattern: MovementPattern.HINGE, difficulty: ExerciseDifficulty.BEGINNER, instructions: ["Hold dumbbells in front of your thighs.","Hinge hips back while lowering weights.","Return to standing with control."], safetyNotes: ["Use a comfortable range and neutral spine."], equipment: ["Dumbbells"] },
    { name: "Leg press", slug: "leg-press", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes"], movementPattern: MovementPattern.SQUAT, difficulty: ExerciseDifficulty.BEGINNER, instructions: ["Set the seat so knees are comfortably bent.","Press platform away without locking knees.","Lower slowly to a comfortable depth."], safetyNotes: ["Do not allow the lower back to round."], equipment: ["Leg Press"] },
    { name: "Dumbbell reverse lunge", slug: "dumbbell-reverse-lunge", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes"], movementPattern: MovementPattern.LUNGE_CARRY, difficulty: ExerciseDifficulty.INTERMEDIATE, instructions: ["Step one foot backward.","Lower both knees with control.","Push through the front foot to return."], safetyNotes: ["Hold a support if balance is limited."], equipment: ["Dumbbells"] },
    { name: "Glute bridge", slug: "glute-bridge", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings","Core"], movementPattern: MovementPattern.HINGE, difficulty: ExerciseDifficulty.BEGINNER, instructions: ["Lie on your back with knees bent.","Lift hips while keeping ribs down.","Lower with control."], safetyNotes: ["Avoid arching through the lower back."], equipment: ["Bodyweight Only"] },
    { name: "Plank", slug: "plank", primaryMuscle: "Core", secondaryMuscles: ["Shoulders"], movementPattern: MovementPattern.ROTATION, difficulty: ExerciseDifficulty.BEGINNER, instructions: ["Place forearms on the floor.","Brace gently and keep a straight line.","Hold while breathing steadily."], safetyNotes: ["Stop if you feel pain in your back or shoulders."], equipment: ["Bodyweight Only"] },
    { name: "Cable chest fly", slug: "cable-chest-fly", primaryMuscle: "Chest", secondaryMuscles: ["Shoulders"], movementPattern: MovementPattern.OTHER, difficulty: ExerciseDifficulty.INTERMEDIATE, instructions: ["Stand centered between cable handles.","Bring hands together in a comfortable arc.","Return slowly without letting shoulders roll forward."], safetyNotes: ["Use a light load and controlled motion."], equipment: ["Cable Machine"] },
    { name: "Incline dumbbell press", slug: "incline-dumbbell-press", primaryMuscle: "Chest", secondaryMuscles: ["Triceps","Shoulders"], movementPattern: MovementPattern.HORIZONTAL_PUSH, difficulty: ExerciseDifficulty.INTERMEDIATE, instructions: ["Set bench at a modest incline.","Lower dumbbells with control.","Press up without clanking weights."], safetyNotes: ["Use a spotter when lifting challenging loads."], equipment: ["Dumbbells","Bench"] },
    { name: "Resistance band row", slug: "resistance-band-row", primaryMuscle: "Back", secondaryMuscles: ["Biceps"], movementPattern: MovementPattern.HORIZONTAL_PULL, difficulty: ExerciseDifficulty.BEGINNER, instructions: ["Anchor band securely at chest height.","Pull elbows back while keeping shoulders relaxed.","Return slowly."], safetyNotes: ["Check the band and anchor for damage before use."], equipment: ["Resistance Bands"] },
  ];
  const exercises = Object.fromEntries(await Promise.all(exerciseData.map(async ({ equipment: requirements, ...data }) => {
    const exercise = await prisma.exercise.upsert({ where: { slug: data.slug }, update: data, create: data });
    for (const item of requirements) await prisma.exerciseEquipment.upsert({ where: { exerciseId_equipmentId: { exerciseId: exercise.id, equipmentId: equipment[item].id } }, update: {}, create: { exerciseId: exercise.id, equipmentId: equipment[item].id } });
    return [data.slug, exercise] as const;
  })));
  await prisma.foodAlternative.upsert({ where: { sourceFoodId_alternativeFoodId: { sourceFoodId: foods["greek-yogurt"].id, alternativeFoodId: foods["firm-tofu"].id } }, update: {}, create: { sourceFoodId: foods["greek-yogurt"].id, alternativeFoodId: foods["firm-tofu"].id, rationale: "Plant-based protein alternative" } });
  await prisma.foodAlternative.upsert({ where: { sourceFoodId_alternativeFoodId: { sourceFoodId: foods["greek-yogurt"].id, alternativeFoodId: foods["cottage-cheese"].id } }, update: {}, create: { sourceFoodId: foods["greek-yogurt"].id, alternativeFoodId: foods["cottage-cheese"].id, rationale: "Dairy-based high-protein alternative" } });
  await prisma.exerciseAlternative.upsert({ where: { sourceExerciseId_alternativeExerciseId: { sourceExerciseId: exercises["barbell-bench-press"].id, alternativeExerciseId: exercises["dumbbell-floor-press"].id } }, update: {}, create: { sourceExerciseId: exercises["barbell-bench-press"].id, alternativeExerciseId: exercises["dumbbell-floor-press"].id, rationale: "Chest press variation requiring only dumbbells" } });
  await prisma.exerciseAlternative.upsert({ where: { sourceExerciseId_alternativeExerciseId: { sourceExerciseId: exercises["barbell-bench-press"].id, alternativeExerciseId: exercises["push-up"].id } }, update: {}, create: { sourceExerciseId: exercises["barbell-bench-press"].id, alternativeExerciseId: exercises["push-up"].id, rationale: "Bodyweight horizontal press" } });
  for (const [source,target,rationale] of [["chicken-breast","firm-tofu","Plant-based protein option"],["chicken-breast","lentils-cooked","Plant-based legume option"],["salmon","firm-tofu","Plant-based option with a different fat profile"],["brown-rice-cooked","quinoa-cooked","Whole grain alternative"]]) await prisma.foodAlternative.upsert({ where: { sourceFoodId_alternativeFoodId: { sourceFoodId: foods[source].id, alternativeFoodId: foods[target].id } }, update: { rationale }, create: { sourceFoodId: foods[source].id, alternativeFoodId: foods[target].id, rationale } });
  for (const [source,target,rationale] of [["lat-pulldown","resistance-band-row","Band-based back movement for days without a cable station"],["romanian-deadlift","dumbbell-romanian-deadlift","Hinge pattern using dumbbells"],["leg-press","dumbbell-goblet-squat","Squat pattern using dumbbells"]]) await prisma.exerciseAlternative.upsert({ where: { sourceExerciseId_alternativeExerciseId: { sourceExerciseId: exercises[source].id, alternativeExerciseId: exercises[target].id } }, update: { rationale }, create: { sourceExerciseId: exercises[source].id, alternativeExerciseId: exercises[target].id, rationale } });
  console.log(`Seeded ${goalLabels.length} goal choices, ${physiqueData.length} physique archetypes, ${foodData.length} foods, ${exerciseData.length} exercises, and ${equipmentData.length} equipment items.`);
}

function slug(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }

main().catch((error) => { console.error(error); process.exit(1); }).finally(async () => prisma.$disconnect());
