import { randomUUID } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { NextResponse } from "next/server";
import { requireUser } from "@/lib/auth";
import { apiError } from "@/lib/api";
import { FitPlanError } from "@/lib/errors";
import { prisma } from "@/lib/prisma";
export const runtime="nodejs";
const MAX_SIZE=5*1024*1024;
function detectImage(bytes:Buffer){if(bytes.length>=3&&bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)return"image/jpeg";if(bytes.length>=8&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return"image/png";if(bytes.length>=12&&bytes.toString("ascii",0,4)==="RIFF"&&bytes.toString("ascii",8,12)==="WEBP")return"image/webp";return null;}
export async function POST(request:Request){try{const user=await requireUser();const form=await request.formData();const file=form.get("file");if(!(file instanceof File))throw new FitPlanError("VALIDATION_ERROR","Choose an image to upload.");if(file.size>MAX_SIZE||file.size===0)throw new FitPlanError("VALIDATION_ERROR","Images must be smaller than 5 MB.");if(!["image/jpeg","image/png","image/webp"].includes(file.type))throw new FitPlanError("VALIDATION_ERROR","Use a JPEG, PNG, or WebP image.");const bytes=Buffer.from(await file.arrayBuffer());const mime=detectImage(bytes);if(!mime||mime!==file.type)throw new FitPlanError("VALIDATION_ERROR","The uploaded file does not match a supported image format.");const profile=await prisma.profile.findUnique({where:{userId:user.id},select:{id:true}});if(!profile)throw new FitPlanError("INVALID_PROFILE","Create your profile before uploading a reference image.");const key=`${user.id}/${randomUUID()}.${mime==="image/jpeg"?"jpg":mime==="image/png"?"png":"webp"}`;const root=path.resolve(process.env.FITPLAN_UPLOAD_DIR??path.join(process.cwd(),".private-uploads"));const target=path.resolve(root,key);if(!target.startsWith(`${root}${path.sep}`))throw new FitPlanError("VALIDATION_ERROR","Invalid upload path.");await mkdir(path.dirname(target),{recursive:true});await writeFile(target,bytes,{flag:"wx",mode:0o600});try{const image=await prisma.referenceImage.create({data:{userId:user.id,profileId:profile.id,storageKey:key,mimeType:mime,sizeBytes:file.size,altText:"Private physique reference image"}});return NextResponse.json({image:{id:image.id,mimeType:image.mimeType,sizeBytes:image.sizeBytes,createdAt:image.createdAt}},{status:201});}catch(error){const {unlink}=await import("node:fs/promises");await unlink(target).catch(()=>{});throw error;}}catch(error){return apiError(error);}}
